spring.datasource.url=jdbc:mysql://localhost:3306/infant_meal_db?serverTimezone=Asia/Seoul&useSSL=false
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

clova.ocr.url=YOUR_CLOVA_OCR_URL
clova.ocr.secret=YOUR_CLOVA_OCR_SECRET

server.port=8080
